version: '3.8'
services:

  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  backend:
    build:
      context: ./backend
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080

  frontend:
    build: ./frontend
    ports:
      - 4200:4200